### ISSUE TITLE
url() references in CSS files don’t work in dev mode

### ISSUE THREAD

**Issue by sephii** [MrBin99/django-vite#43]
I have the following files structure:

```
assets/
  css/index.css
  fonts/myfont.woff2
```

Using the following in `css/index.css`:

```css
@font-face {
  font-family: myfont;
  src: url(../fonts/myfont.woff2);
}

body {
  font-family: myfont;
}
```

Produces the following when loading the stylesheet on http://localhost:3000/static/assets/css/index.css:

```css
@font-face {
  font-family: myfont;
  src: url("/static/assets/fonts/Simple-Line-Icons.woff2");
}
```

Which I would expect to work, but for some reason my browser (Firefox 99.0.1) tries to load the font from http://localhost:8000/static/assets/css/index.css, which of course fails (trying to access http://localhost:3000/static/assets/css/index.css works though). I’m not sure what’s happening here (I thought `url()` was relative to the CSS file, not to the page), but I could also see a lot of 404s to `http://localhost:8000/static/__vite_ping`. Looking at the @vite/client source, it seems that it’s doing fetch requests to `${base}__vite_ping`, where `${base}` is the base defined in the vite config. I’m not sure these 2 problems are related, but maybe the vite client does fetch requests for the assets or something like that?

I tried changing `base` to http://localhost:3000/static/ in my vite config, but it seems that the hostname part gets stripped so it didn’t change anything.

I was able to hack around this problem by adding `BASE_DIR` to my `STATICFILES_DIRS` in dev, but that’s really ugly.
