### ISSUE TITLE
Connection settings with docker-compose setup

### ISSUE THREAD

**Issue by kylelmh** [MrBin99/django-vite#45]
Hey there,
Many thanks for creating this package.

I am currently developing a web app with separate containers for `node` and `python` with the following docker-compose setup
```yaml
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - vite-dist:/code/frontend/dist
    ports:
      - "8000:8000"
  vite:
    build:
      context: frontend
    command: npm run dev --port=3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/vite
      - vite-nodes:/vite/node_modules
      - vite-dist:/vite/dist
 
volumes:
  vite-dist:
  vite-nodes:
```

In this case, django will load the vite packages at `localhost:3000` and everything works fine.
However, connections cannot be established if I close the port on `3000` for `vite`.
**I was wondering if there is any way to load the required scripts with internal docker connections, similar to how django connects to databases.**  What are your thoughts on this.
i.e. `vite:3000`

Note: 
- Changing `DJANGO_VITE_DEV_SERVER_HOST = 'vite'` results in an unresolved hostname.
- I believe this would only be an issue in debugging, as the compiled static files will be collected during production.
